version: 1.0.0.{build}

image: Visual Studio 2019

environment:
  packageVersion: 1.0.0

init:
- ps: echo "$env:packageVersion"
- ps: $env:nugetVersion = "$env:packageVersion"
- ps: echo "$env:nugetVersion"

configuration: Release

platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(nugetVersion)
  assembly_version: '{version}'
  file_version: $(nugetVersion)
  informational_version: $(nugetVersion)

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

after_build:
- ps: dotnet pack Promat.Windows.FirewallManagement\Promat.Windows.FirewallManagement.csproj --configuration Release --include-symbols --no-build --output "$env:APPVEYOR_BUILD_FOLDER"

artifacts:
- path: '*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: hUOSiR+ofJ7TXViTl4OEPpBHHrx3koT8CG1EeOCj/zCTqdj5/QFRiRglUvTsuUw3
  skip_symbols: true
  on:
    APPVEYOR_REPO_TAG: true
